// Generates content/index.json (the content files the app loads) and
// precache.js (everything the service worker stores for offline use).
// Run after any change: node tools/build-index.mjs
import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const contentDir = join(root, 'content');

const files = [];
for (const d of readdirSync(contentDir)) {
  const p = join(contentDir, d);
  if (!statSync(p).isDirectory()) continue;
  for (const f of readdirSync(p)) if (f.endsWith('.json')) files.push(`${d}/${f}`);
}
files.sort();
writeFileSync(join(contentDir, 'index.json'), JSON.stringify({ files }, null, 1) + '\n');

const walk = (dir) => readdirSync(dir).flatMap((f) => {
  const p = join(dir, f);
  return statSync(p).isDirectory() ? walk(p) : [p];
});
const appFiles = [
  'index.html', 'styles.css', 'manifest.webmanifest',
  ...walk(join(root, 'js')).map((p) => relative(root, p)),
  ...walk(join(root, 'icons')).map((p) => relative(root, p)),
  'content/taxonomy.json', 'content/index.json',
  ...files.map((f) => `content/${f}`),
].map((p) => p.split('\\').join('/')).filter((p) => existsSync(join(root, p)));

const hash = createHash('sha256');
for (const p of appFiles) hash.update(p).update(readFileSync(join(root, p)));
hash.update(readFileSync(join(root, 'sw.js')));
const version = hash.digest('hex').slice(0, 12);

const precache = ['./', ...appFiles];
writeFileSync(join(root, 'precache.js'),
  `// Generated by tools/build-index.mjs. Do not edit.\nself.VERSION = '${version}';\nself.PRECACHE = ${JSON.stringify(precache, null, 1)};\n`);
console.log(`${files.length} content files, ${precache.length} precached, version ${version}`);
